In [5]:
import a2c
import gym
import torch

In [6]:
env = gym.make('CartPole-v0')
a2c_net = a2c.a2c.A2C(N=100, nA=2, actor=a2c.net.NeuralNet(4, 2, torch.nn.functional.softmax), critic=a2c.NeuralNet(4, 2, torch.nn.functional.softmax), actor_lr=5e-4, critic_lr=1e-4, type="Reinforce")

a2c_net.generate_episode(env, render=True)


Training with Reinforce.


([array([-0.02638893,  0.04096145, -0.04231221, -0.00429941]),
  array([-0.02556971,  0.23666387, -0.04239819, -0.31002639]),
  array([-0.02083643,  0.43236344, -0.04859872, -0.61577328]),
  array([-0.01218916,  0.6281295 , -0.06091419, -0.92335805]),
  array([ 3.73430377e-04,  8.24019134e-01, -7.93813479e-02, -1.23454523e+00]),
  array([ 0.01685381,  1.02006664, -0.10407225, -1.55100406]),
  array([ 0.03725515,  1.21627164, -0.13509233, -1.87426121]),
  array([ 0.06158058,  1.41258539, -0.17257756, -2.20564533])],
 [1, 1, 1, 1, 1, 1, 1, 1],
 [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])

In [7]:
s0 = [ 0.03666531,  0.0214262 ,  0.01976534, -0.01147768]
print(a2c_net.actor(torch.Tensor(s0)))
for _ in range(100):
    a2c_net.train(env)
print(a2c_net.actor(torch.Tensor(s0)))

tensor([0.4500, 0.5500], grad_fn=<SoftmaxBackward0>)
tensor([0.0760, 0.9240], grad_fn=<SoftmaxBackward0>)


In [8]:
a2c_net.evaluate_policy_episodes(env, num_episodes=100).mean()

9.4